### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Code-Shy** [zm17943/SplitAVG#1]
```
Traceback (most recent call last):
  File "D:\Project\DeepLearning\SplitAVG\main_SplitAVG.py", line 141, in <module>
    main()
  File "D:\Project\DeepLearning\SplitAVG\main_SplitAVG.py", line 118, in main
    running_loss = splitavg_propagation(arg, server_net, chosen_net, generators, arg.device, criterion, optimizers, optimizer_server)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Project\DeepLearning\SplitAVG\util.py", line 69, in splitavg_propagation
    grad_to_send = feature_cat.grad[0*arg.batch_size:(0+1)*arg.batch_size]
                   ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

I encountered the above error when running the code, which shows that the grad of feature_cat is None. Could you share how the author resolved this issue?

**Comment by song2000012138** [comment]
The project is so weird, I guess It's just can't work.

**Comment by zm17943** [comment]
Hi @Code-Shy! It looks from your error that `feature_cat` does not get the grad created or retained, could you double check if `loss.backward()` at line 58 succeeds? Since the loss is computed based on `feature_cat`, the gradients of the variable will be generated when loss is backward propagated. I'd like to take a look at other parts of your codes to help debug.

The output of running the codes with provided data would look like: 
<img width="1229" alt="Screenshot 2023-12-07 at 9 45 48 AM" src="https://github.com/zm17943/SplitAVG/assets/30038903/dbcc0811-1251-4feb-8a55-53cdc9a42d93">
